name:                Spock-example
version:             0.1.0.0
github:              "mingyuchoo/Spock-example"
license:             BSD3
author:              "Mingyu Choo"
maintainer:          "mingyuchoo@gmail.com"
copyright:           "Mingyu Choo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/Spock-example#readme>

dependencies:
- base >= 4.9.1.0 && < 5
- containers
- focus
- http-types
- monad-logger
- mtl
- parallel
- persistent
- persistent-template
- persistent-sqlite
- primitive-extras
- primitive-unlifted
- reroute
- stm-containers
- stm-hamt
- text
- Spock
- Spock-core

default-extensions: []
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Spock-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - Spock-example

tests:
  Spock-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - Spock-example
