name:                scotty-t01-shortener
version:             0.1.0.0
github:              "githubuser/scotty-t01-shortener"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/scotty-t01-shortener#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-html
- containers
- http-types
- scotty
- text
- doctest
- doctest-discover

library:
  source-dirs: src

executables:
  scotty-t01-shortener-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scotty-t01-shortener

tests:
  scotty-t01-shortener-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scotty-t01-shortener
