# https://www.stackage.org/lts-23.19
resolver: lts-23.19

packages:
- .

extra-package-dbs: []
extra-deps: []
flags: {}

docker:
  enable: true
  repo: fpco/stack-build:lts-23.19
  auto-pull: true
  detach: false
  persist: false
  container-name: "socket-echo-server"
  run-args: []
  stack-exe: host
  set-user: true

# nix:
#   enable: true
#   pure: true
#   packages:
#   - zlib
#   - glpk
#   - pcre
#   #shell-file: shell.nix
#   nix-shell-options: []
#   path: []
#   add-gc-roots: false
