# https://www.stackage.org/lts-23.18
resolver: lts-23.18

packages:
- .

extra-package-dbs: []
extra-deps: []
flags: {}

nix:
  enable: true
  pure: true
  packages:
  - zlib
  - glpk
  - pcre
  #shell-file: shell.nix
  nix-shell-options: []
  path: []
  add-gc-roots: false
